In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
train = pd.read_pickle(
    "../data/train_clean.pkl"
)

print(train.shape)

(590540, 426)

In [3]:
train.isnull().sum().sum()

np.int64(0)

In [4]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [5]:
train = pd.read_pickle("../data/train_clean.pkl")

print(train.shape)

(590540, 426)

In [6]:
#1. Log transaction amount
train["TransactionAmt_log"] = np.log1p(
    train["TransactionAmt"]
)

In [7]:
#2. email domain feture
train["P_email_prefix"] = (
    train["P_emaildomain"]
    .astype(str)
    .str.split(".")
    .str[0]
)

In [8]:
#3. Mobile device flag
train["is_mobile"] = (
    train["DeviceType"] == "mobile"
).astype(int)

In [9]:
# Transaction Amount bins
train["Amt_Bin"] = pd.qcut(
    train["TransactionAmt"],
    q=10,
    duplicates="drop"
)

In [10]:
# Card frequency feature
train["card1_frequency"] = (
    train.groupby("card1")["card1"]
    .transform("count")
)

In [14]:
# Frequency Feature
train["card1_frequency"] = (
    train.groupby("card1")["card1"]
    .transform("count")
)

train["email_frequency"] = (
    train.groupby("P_emaildomain")["P_emaildomain"]
    .transform("count")
)

In [15]:
train[
    [
        "TransactionAmt",
        "TransactionAmt_log",
        "P_emaildomain",
        "P_email_prefix",
        "DeviceType",
        "is_mobile",
        "Amt_Bin",
        "card1_frequency",
        "email_frequency"
    ]
].head()

,TransactionAmt,TransactionAmt_log,P_emaildomain,P_email_prefix,DeviceType,is_mobile,Amt_Bin,card1_frequency,email_frequency
0,68.5,4.241327,Missing,Missing,Missing,0,"(57.95, 68.769]",43,94456
1,29.0,3.401197,gmail.com,gmail,Missing,0,"(25.95, 35.95]",683,228355
2,59.0,4.094345,outlook.com,outlook,Missing,0,"(57.95, 68.769]",1108,5096
3,50.0,3.931826,yahoo.com,yahoo,Missing,0,"(49.0, 57.95]",4209,100934
4,50.0,3.931826,gmail.com,gmail,mobile,1,"(49.0, 57.95]",18,228355

In [ ]:
# Email domain frequency feature
train["email_frequency"] = (
    train.groupby("P_emaildomain")
    ["P_emaildomain"]
    .transform("count")
)

In [12]:
train[
[
"TransactionAmt",
"TransactionAmt_log",
"is_mobile",
"card1_frequency",
"email_frequency"
]
].head()

,TransactionAmt,TransactionAmt_log,is_mobile,card1_frequency,email_frequency
0,68.5,4.241327,0,43,94456
1,29.0,3.401197,0,683,228355
2,59.0,4.094345,0,1108,5096
3,50.0,3.931826,0,4209,100934
4,50.0,3.931826,1,18,228355

In [17]:
# saving the feature engineered dataset
train.to_pickle(
    "../data/train_feature_engineered.pkl"
)

print("Feature Engineering Saved")

Feature Engineering Saved

In [19]:
train.shape

(590540, 432)