In [4]:
import pandas as pd

train = pd.read_pickle(
    "../data/train_feature_engineered.pkl"
)

print(train.shape)

(590540, 432)

In [5]:
train[
    [
        "TransactionAmt",
        "card1",
        "card2",
        "card6",
        "card1_frequency",
        "email_frequency",
        "TransactionDT",
        "D1",
        "D2",
        "C1",
        "isFraud"
    ]
].sample(10)

,TransactionAmt,card1,card2,card6,card1_frequency,email_frequency,TransactionDT,D1,D2,C1,isFraud
268732,65.000,1101,555.0,debit,13,100934,6499610,2.0,2.0,3.0,0
406606,107.950,1342,514.0,debit,1321,94456,10269252,54.0,54.0,7.0,0
122371,44.990,10254,360.0,debit,12,228355,2404709,15.0,15.0,1.0,0
475009,107.950,6194,498.0,debit,302,228355,12268872,619.0,619.0,2.0,0
55573,57.950,17410,555.0,debit,30,94456,1290116,235.0,235.0,60.0,0
210275,25.950,2884,490.0,debit,3873,7888,4851467,241.0,241.0,102.0,0
541158,53.970,10993,555.0,debit,6,100934,14261626,637.0,415.0,3.0,0
438585,87.000,9921,555.0,debit,34,100934,11117315,0.0,97.0,1.0,0
404994,67.067,3154,408.0,debit,4614,45250,10236915,0.0,97.0,1.0,0
466284,57.950,4436,174.0,debit,1947,228355,12003205,45.0,45.0,1.0,0

Sepersting Fraud and Non Fraud Samples

In [6]:
# Fraud
fraud_sample = train[
    train["isFraud"] == 1
][
    [
        "TransactionAmt",
        "card1",
        "card2",
        "card6",
        "card1_frequency",
        "email_frequency",
        "TransactionDT",
        "D1",
        "D2",
        "C1",
        "isFraud"
    ]
].sample(5, random_state=42)

fraud_sample

,TransactionAmt,card1,card2,card6,card1_frequency,email_frequency,TransactionDT,D1,D2,C1,isFraud
54132,44.000,11233,321.0,debit,597,228355,1273596,393.0,393.0,1.0,1
495177,39.470,9026,545.0,credit,2076,36998,12943155,0.0,97.0,1.0,1
79506,31.482,5812,408.0,debit,2818,45250,1719967,0.0,97.0,2.0,1
313170,21.993,12730,266.0,credit,218,228355,7786409,0.0,97.0,1.0,1
526937,59.000,7664,490.0,debit,2792,228355,13869768,189.0,189.0,1.0,1

In [7]:
# Non fraud
nonfraud_sample = train[
    train["isFraud"] == 0
][
    [
        "TransactionAmt",
        "card1",
        "card2",
        "card6",
        "card1_frequency",
        "email_frequency",
        "TransactionDT",
        "D1",
        "D2",
        "C1",
        "isFraud"
    ]
].sample(5, random_state=42)

nonfraud_sample

,TransactionAmt,card1,card2,card6,card1_frequency,email_frequency,TransactionDT,D1,D2,C1,isFraud
219206,25.00,8406,264.0,debit,1085,228355,5151894,0.0,97.0,1.0,0
187783,200.00,18080,111.0,credit,55,36998,4202454,24.0,24.0,1.0,0
35892,146.00,8406,264.0,debit,1085,228355,869878,0.0,97.0,1.0,0
31989,57.95,11218,579.0,debit,957,228355,783090,403.0,403.0,4.0,0
66086,49.00,12570,462.0,debit,314,100934,1479490,39.0,39.0,2.0,0